const String BASE_URL='http://10.0.2.2:3000/api/owner';
const String REQUEST_SUCCESS = "REQUEST_SUCCESS";
const String REQUEST_NETWORK_ERROR = "REQUEST_NETWORK_ERROR";
const String REQUEST_FAIL = "REQUEST_FAIL";